import type { AppShortcutContract } from '../shared/contracts.js';

export type MockApp = AppShortcutContract;

function browserAllowedHosts() {
  const configured = process.env.ETHERDESK_BROWSER_ALLOWED_HOSTS?.split(',')
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);

  return configured && configured.length > 0 ? configured : ['rafex.dev', 'duckduckgo.com', 'housedb.rafex.app'];
}

export const mockApps: MockApp[] = [
  {
    id: 'browser',
    name: 'Browser',
    description: 'Navegador web conceptual dentro de EtherDesk.',
    icon: 'browser',
    route: '/apps/browser',
    allowedHosts: browserAllowedHosts(),
    type: 'integration',
    origin: 'internal',
    permissions: ['browser.navigate'],
  },
  {
    id: 'notes',
    name: 'Notes',
    description: 'Editor ligero de texto con CodeMirror.',
    icon: 'notes',
    route: '/apps/notes',
    type: 'workspace',
    origin: 'internal',
    permissions: ['notes.read', 'notes.write', 'files.read'],
  },
  {
    id: 'ide',
    name: 'IDE',
    description: 'Editor avanzado con Monaco para el documento activo.',
    icon: 'ide',
    route: '/apps/ide',
    type: 'workspace',
    origin: 'internal',
    permissions: ['notes.read', 'notes.write', 'files.read'],
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Terminal controlada.',
    icon: 'terminal',
    route: '/apps/terminal',
    type: 'workspace',
    origin: 'internal',
    permissions: ['terminal.execute.controlled', 'files.read'],
  },
  {
    id: 'files',
    name: 'Files',
    description: 'Explorador minimo de archivos locales del workspace.',
    icon: 'files',
    route: '/apps/files',
    type: 'workspace',
    origin: 'internal',
    permissions: ['files.read', 'files.write', 'notes.read', 'terminal.execute.controlled'],
  },
  {
    id: 'system-monitor',
    name: 'System Monitor',
    description: 'Estado del sistema web, kernel y PWA.',
    icon: 'monitor',
    route: '/apps/system-monitor',
    type: 'system',
    origin: 'internal',
    permissions: ['monitor.read'],
  },
  {
    id: 'notification-center',
    name: 'Notifications',
    description: 'Centro completo de notificaciones y eventos.',
    icon: 'notifications',
    route: '/apps/notifications',
    type: 'system',
    origin: 'internal',
    permissions: ['notifications.read'],
  },
  {
    id: 'settings',
    name: 'Settings',
    description: 'Configuracion visual del sistema.',
    icon: 'settings',
    route: '/apps/settings',
    type: 'system',
    origin: 'internal',
    permissions: ['settings.write'],
  },
  {
    id: 'account',
    name: 'Account',
    description: 'Perfil, sesion y estado del usuario.',
    icon: 'account',
    route: '/apps/account',
    type: 'system',
    origin: 'internal',
    permissions: ['account.read'],
  },
  {
    id: 'tasks',
    name: 'Tasks',
    description: 'Trabajos pendientes y sincronizaciones offline.',
    icon: 'tasks',
    route: '/apps/tasks',
    type: 'system',
    origin: 'internal',
    permissions: ['tasks.read'],
  },
  {
    id: 'help',
    name: 'Help',
    description: 'Guia rapida del sistema y sus limitaciones.',
    icon: 'help',
    route: '/apps/help',
    type: 'system',
    origin: 'internal',
    permissions: ['help.read'],
  },
  {
    id: 'tars-chat',
    name: 'TARS Chat',
    description: 'Asistente local del sistema para ayuda rapida.',
    icon: 'chat',
    route: '/apps/tars-chat',
    type: 'core',
    origin: 'internal',
    permissions: ['help.read', 'notifications.read'],
  },
];
